workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "test"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - when: never

stages:
  - build
  - test
  - package

include:
  - local: ".gitlab/ci/templates/rpm-build.yaml"
  - local: ".gitlab/ci/templates/test.yaml"
  - local: ".gitlab/ci/build/el9-build.yaml"
  - local: ".gitlab/ci/build/el10-build.yaml"
  - local: ".gitlab/ci/build/fedora42-build.yaml"
  - local: ".gitlab/ci/build/fedora43-build.yaml"
  - local: ".gitlab/ci/test/el9-test.yaml"
  - local: ".gitlab/ci/test/el10-test.yaml"
  - local: ".gitlab/ci/test/fedora42-test.yaml"
  - local: ".gitlab/ci/test/fedora43-test.yaml"
